app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('ova.urls')),
    path('', include('usuario.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="usuario"
urlpatterns = [
    # path('',views.index, name='index'),
    path('login',views.loginView, name='login'),
    path('logout', views.logoutView, name="logout"),
    path('registro', views.registerView, name='registro'),
    path('perfil',views.perfil, name='perfil'),
    path('perfil/datos',views.editar_datos, name='datos'),
    path('perfil/password',views.change_password, name='change'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, BaseUserManager)
from django.contrib.auth.models import AbstractUser

from django.utils import timezone

from ova.models import Actividad
# Modelos de la base de datos relacionados a los usuarios clientes o administrador

class UserProfileManager(BaseUserManager):
    """ Manager del Modelo de Perfil de Usarios """

    def create_user(self, email, name, apellidos, password=None):
        """ Crear nuevo UserProfile"""
        if not email:
            raise ValueError('Usuario debe tener un email')

        email = self.normalize_email(email)
        user = self.model(email=email, name=name, apellidos=apellidos)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, name, apellidos, password):
        """ Crear un Super Usuario"""
        user = self.create_user(email, name, apellidos, password)
        user.is_superuser = True
        user.is_staff = True

        user.save(using=self._db)

        return user


class UserProfile(AbstractBaseUser, PermissionsMixin):
    """ Modelo Base de datos para Usuarios en el Sistema """
    email = models.EmailField('Email', max_length=255, unique=True)
    name = models.CharField('Nombres', max_length=100)
    apellidos = models.CharField('Apellidos', max_length=100)
    direccion = models.CharField('Direccion', max_length=500)
    celular = models.CharField('Celular', max_length=20, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)

    class Meta:
        swappable = 'AUTH_USER_MODEL'

    class Meta(AbstractUser.Meta):
        pass

    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', "apellidos"]

    def get_full_name(self):
        ''' Obtener nombre completo del usuario'''
        return self.name

    def get_short_name(self):
        ''' Obtener nombre corto del usuario '''
        return self.name

    def __str__(self):
        ''' Obtener cadena representativa de nuestro usuario '''
        return self.name

class Puntaje(models.Model):
    usuario = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE)
    resultado = models.DecimalField('Resultado', max_digits=5, decimal_places=2)
    is_sumativo = models.BooleanField(default=False)

    def __str__(self):
        ''' Obtener cadena representativa de nuestro usuario '''
        return f"{self.usuario} nota: {self.resultado}"

usuario/forms.py
from django import forms

from django import forms
from django.core.exceptions import ValidationError
from .models import (UserProfile)


#Formularios

class LoginForm(forms.Form):
    """ Formulario de Login para Gerente y Empleado"""
    email = forms.CharField(label='Email ', required=True)
    password = forms.CharField(label='Contraseña ', widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
     required=True)


class RegistroForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'apellidos', 'direccion', 'email', 'password', 'celular']


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'apellidos', 'celular', 'email','direccion']

class CambiarPasswordForm(forms.ModelForm):
    password_confirm = forms.CharField( label="Confirmar Contraseña", max_length=100, widget=forms.PasswordInput(attrs={'placeholder': '•••••••••'}))
    class Meta:
        model = UserProfile
        fields = ['password']
        widgets = {
            'password': forms.PasswordInput(attrs={'placeholder': '••••••••••'}),
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password != password_confirm:
            raise ValidationError("Las contraseñas no coinciden.")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

usuario/views.py
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render, redirect
from django.contrib.auth import (login, logout)
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from django.http import JsonResponse
from .models import (UserProfile)

from .forms import (LoginForm, RegistroForm, UsuarioForm, CambiarPasswordForm)
from django.db.models import F, ExpressionWrapper, DecimalField, Sum
from decimal import Decimal
from django.utils import timezone
from  usuario.utils import createLessonScore


def loginView(request):
    if request.user.is_superuser:
        return redirect('/admin')
    
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        try:
            usuario = UserProfile.objects.get(email=email)
            if usuario is not None and usuario.check_password(password):
                login(request, usuario)
                return redirect('producto:inicio') if usuario.is_superuser else redirect('/')
            else:
                messages.error(request, "Contraseña incorrecta")
        except Exception as e:
            messages.error( request, "Lo sentimos, no pudimos encontrar tu cuenta")
            usuario = None
            print(e)
    form = LoginForm()
    return render(request, 'login.html', {'form': form})


def index(request):
  
    return render(request, 'index.html')



def logoutView(request):
    logout(request)
    return redirect('/')

def registerView(request):
    if not request.user.is_anonymous: 
        messages.error(request, "Cierre sesión antes de registrar otro usuario.")
        return redirect('/login')
    
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        apellido = request.POST.get('apellido')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        
        # Validaciones básicas
        if not all([nombre, apellido, email, password]):
            messages.error(request, "Todos los campos son obligatorios.")
        elif password != confirm_password:
            messages.error(request, "Las contraseñas no coinciden.")
        elif UserProfile.objects.filter(email=email).exists():
            messages.error(request, "El email ya está registrado.")
        else:
            # Crear el nuevo usuario
            user = UserProfile.objects.create_user(
                email=email,
                password=password,
                name=nombre,
                apellidos=apellido
            )
            createLessonScore(user)
            messages.success(request, "Usuario registrado exitosamente.")
            return redirect('usuario:login')
    
    return render(request, 'registro.html')


def perfil(request):
    usuario = request.user
    form = UsuarioForm(instance=usuario)
    form1 = CambiarPasswordForm()

    context = {
        "form": form,
        "form1": form1,
    }
    
    return render(request, 'perfil.html', context)

def editar_datos(request):
    usuario = request.user
    form1 = CambiarPasswordForm()

    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
       
        if form.is_valid():
            password = request.POST.get('password')
            usuario = form.save()
            
            messages.success(request, 'El usuario fue actualizado correctamente')
            return redirect('usuario:login')

    else:
        form = UsuarioForm(instance=usuario)

    context = {
        "form": form,
        "form1": form1
    }
    
    
    # Renderizar el template con los productos
    return render(request, 'perfil.html', context)

def change_password(request):
    usuario = request.user

    form = UsuarioForm(instance=usuario)
    if request.method == 'POST':
        form1 = CambiarPasswordForm(request.POST)
        if form1.is_valid():
            usuario.set_password(form1.cleaned_data['password'])
            usuario.save()
            messages.success(request, 'Contraseña actualizada correctamente')
            return redirect('usuario:login')
    else:
        form1 = CambiarPasswordForm()

    context = {
        "form": form,
        "form1": form1
    }
    context.update(subcategorias(request))
    
    # Renderizar el template con los productos
    return render(request, 'perfil.html', context)

usuario/templates/index.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Inicio Sesión
{% endblock title %}

{% block body %}

<h1>Hola jlopez</h1>
<div>
    <a type="button" class="btn btn-danger" href="/login">Ir a login</a>
</div>

{% endblock body %}

usuario/templates/index2.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Inicio Sesión
{% endblock title %}

{% block body %}

<h1>Hola jlopez</h1>
<div>
    <a type="button" class="btn btn-danger" href="/login">Ir a login</a>
</div>

{% endblock body %}

usuario/templates/login.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Inicio Sesión
{% endblock title %}

{% block body %}

<div class="gradient-custom my-auto" style="display: block;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <div>
              {% if messages %}
              <div>
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}">
                  {{message}}
                </div>
                {% endfor %}
              </div>
              {% endif %}
            </div>
            <form method="POST">
              {% csrf_token %}
              <div class="mb-md-5 mt-md-4 pb-5">
                <h2 class="fw-bold mb-4 mt-4 text-uppercase">Inicio de sesión</h2>
                {{form|crispy}}
                <button class="btn btn-outline-light btn-lg px-5" type="submit">Iniciar sesión</button>
              </div>

              <div>
                <p class="mb-0">¿No tienes cuenta? <a href="{% url 'usuario:registro' %}" class="text-white-50 fw-bold">Registrate aquí</a>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

usuario/templates/registro.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Inicio Sesión
{% endblock title %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock extra_css %}

{% block body %}

<body class="img js-fullheight" style="background-image: url(/static/img/login.jpg);">
  <section class="ftco-section">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 text-center mb-5">
          <h2 class="heading-section">Registrate</h2>
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-md-6 col-lg-4">
          <div class="login-wrap p-0">
            <h3 class="mb-4 text-center">Crea una cuenta</h3>
            {% if messages %}
            <div>
              {% for message in messages %}
              <div class="alert alert-{{message.tags}}">
                {{message}}
              </div>
              {% endfor %}
            </div>
            {% endif %}
            <form action="/registro" method="POST" class="signin-form">
              {% csrf_token %}
              <div class="form-group">
                <input id="nombre" name="nombre" type="text" class="form-control" placeholder="Nombre" required>
              </div>
              <div class="form-group">
                <input id="apellido" name="apellido"   type="text" class="form-control" placeholder="Apellido" required>
              </div>
              <div class="form-group">
                <input id="email" name="email" type="text" class="form-control" placeholder="Correo" required>
              </div>
              <div class="form-group">
                <input id="password" name="password" type="password" class="form-control" placeholder="Contraseña" required>
                <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
              </div>
              <div class="form-group">
                <input id="confirm_password"  name="confirm_password" type="password" class="form-control" placeholder="Confirmación de contraseña" required>
                <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
              </div>
              <div class="form-group">
                <button type="submit" class="form-control btn btn-primary submit px-3">Registrarse</button>
              </div>

            </form>

          </div>
        </div>
      </div>
    </div>
  </section>
</body>
{% endblock body %}